# This file was generated by GoReleaser. DO NOT EDIT.
cask "fresh" do
  version "2.1.1"

  on_macos do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_amd64.tar.gz"
      sha256 "db30980be715a25081b7da04f70799681faccfa03b12d69843dc5db51d998f20"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_arm64.tar.gz"
      sha256 "685a5be2f24780db698198d4710edfc5050d4e2d0cb53eed36373a108bb1cf79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_amd64.tar.gz"
      sha256 "d628f58ab03f01f40faf0c9e6da18f689243bcc2c218051f2d4ee2f6a643ba7b"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_arm64.tar.gz"
      sha256 "1627e84f6c3ce1cf08d075a23ddc0f846585b489e4694e21844b99fb4964511b"
    end
  end

  name "fresh"
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fresh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fresh"]
    end
  end

  # No zap stanza required

end
