# This file was generated by GoReleaser. DO NOT EDIT.
cask "fresh" do
  version "2.0.0"

  on_macos do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_amd64.tar.gz"
      sha256 "ecb3bc07a200e592d8b8507e76a56dbf8be9b011be546c9f2f4e8c481969fc0e"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_arm64.tar.gz"
      sha256 "0b1a4eb4d1d88818c2f63fe33fef82f6c01ed291a21f1f016b241f45f58724cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_amd64.tar.gz"
      sha256 "888938b60501eedb3e4760d461eb08a385e71e46c01de1adb3a9e828348bb3b8"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_arm64.tar.gz"
      sha256 "cf8dc56fe973367afa051e13e1c72f1b3ff444471c083a2aa13e159457573d09"
    end
  end

  name "fresh"
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fresh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fresh"]
    end
  end

  # No zap stanza required

end
