# This file was generated by GoReleaser. DO NOT EDIT.
cask "fresh" do
  version "2.1.0"

  on_macos do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_amd64.tar.gz"
      sha256 "6f281d107f029ce3f01d15da6bb3aad7e446e4f9e4d425379762277eb5b1ba4c"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_arm64.tar.gz"
      sha256 "13d2777b7cd34237b940caaf031339f2aab31e1c09013b87e5477a487eb99be8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_amd64.tar.gz"
      sha256 "b7a59bbf0d4e86337cf1236b8193fba5fae2bbca6e1d6bb978135125e2d62f8f"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_arm64.tar.gz"
      sha256 "19d1938bf01f18d635003f85457fa3b1652c3be449210e29304af4bd2ce57d81"
    end
  end

  name "fresh"
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fresh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fresh"]
    end
  end

  # No zap stanza required

end
